/**
 * Auto-Reel Upload API — Receives auto-generated videos from the cron pipeline
 *
 * Endpoints:
 *   POST /api/reels/auto-upload   — Upload a generated reel video
 *   GET  /api/reels/auto-feed     — List auto-generated reels
 *   GET  /api/reels/auto-video/:filename — Stream an auto-generated video
 *   GET  /api/reels/auto-thumb/:filename — Serve a thumbnail
 *
 * Auth: Bearer token from REELS_UPLOAD_SECRET env var
 * Storage: ./uploads/auto-reels/ (ephemeral on Railway, regenerated by cron)
 */
const express = require('express');
const router = express.Router();
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');

// Storage paths — try Railway volume first, then local
const UPLOAD_DIR = fs.existsSync('/data/uploads')
  ? '/data/uploads/auto-reels'
  : path.join(__dirname, '..', 'uploads', 'auto-reels');

const THUMB_DIR = path.join(UPLOAD_DIR, 'thumbs');
const MANIFEST_PATH = path.join(UPLOAD_DIR, 'manifest.json');

// Ensure directories exist
[UPLOAD_DIR, THUMB_DIR].forEach(dir => {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
});

// Load or initialize manifest (tracks all auto-generated reels)
function loadManifest() {
  try {
    if (fs.existsSync(MANIFEST_PATH)) {
      return JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf8'));
    }
  } catch (e) {
    console.error('Auto-reels: Failed to load manifest:', e.message);
  }
  return { videos: [], lastUpdated: null };
}

function saveManifest(manifest) {
  manifest.lastUpdated = new Date().toISOString();
  fs.writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 2));
}

// Auth middleware
function requireAuth(req, res, next) {
  const secret = process.env.REELS_UPLOAD_SECRET;
  if (!secret) {
    return res.status(503).json({ error: 'Upload endpoint not configured (missing REELS_UPLOAD_SECRET)' });
  }

  const authHeader = req.headers.authorization;
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return res.status(401).json({ error: 'Missing or invalid authorization header' });
  }

  const token = authHeader.slice(7);
  if (token !== secret) {
    return res.status(403).json({ error: 'Invalid upload secret' });
  }

  next();
}

/**
 * POST /api/reels/auto-upload
 * Upload an auto-generated reel video.
 * Content-Type: application/json
 * Body: {
 *   video_base64: string,     // Base64-encoded MP4 video
 *   thumb_base64?: string,    // Base64-encoded thumbnail image (optional)
 *   name: string,             // Video title
 *   category: string,         // e.g. "Auto-Reel", "AI Cinematic"
 *   template: string,         // Template used (e.g. "HookFirst", "StatShock")
 *   hook?: string,            // The hook text used
 *   content_theme?: string,   // Content theme/topic
 * }
 */
router.post('/auto-upload', requireAuth, (req, res) => {
  try {
    const {
      video_base64,
      thumb_base64,
      name,
      category = 'Auto-Reel',
      template = 'unknown',
      hook = '',
      content_theme = '',
    } = req.body;

    if (!video_base64) {
      return res.status(400).json({ error: 'Missing video_base64' });
    }

    if (!name) {
      return res.status(400).json({ error: 'Missing name' });
    }

    // Generate unique filename
    const id = crypto.randomBytes(8).toString('hex');
    const timestamp = Date.now();
    const videoFilename = `auto_${id}_${timestamp}.mp4`;
    const thumbFilename = `auto_${id}_${timestamp}.webp`;

    // Save video file
    const videoBuffer = Buffer.from(video_base64, 'base64');
    const videoPath = path.join(UPLOAD_DIR, videoFilename);
    fs.writeFileSync(videoPath, videoBuffer);

    // Save thumbnail if provided
    let thumbUrl = null;
    if (thumb_base64) {
      const thumbBuffer = Buffer.from(thumb_base64, 'base64');
      const thumbPath = path.join(THUMB_DIR, thumbFilename);
      fs.writeFileSync(thumbPath, thumbBuffer);
      thumbUrl = `/api/reels/auto-thumb/${thumbFilename}`;
    }

    // Create video entry
    const entry = {
      id: `auto_${id}`,
      name,
      category,
      source: 'auto-generated',
      url: `/api/reels/auto-video/${videoFilename}`,
      thumb: thumbUrl,
      template,
      hook,
      contentTheme: content_theme,
      fileSize: videoBuffer.length,
      createdAt: new Date().toISOString(),
    };

    // Add to manifest
    const manifest = loadManifest();
    manifest.videos.unshift(entry); // newest first

    // Keep last 100 auto-generated videos (prune old files)
    const MAX_VIDEOS = 100;
    if (manifest.videos.length > MAX_VIDEOS) {
      const removed = manifest.videos.splice(MAX_VIDEOS);
      for (const old of removed) {
        try {
          const oldVideoPath = path.join(UPLOAD_DIR, path.basename(old.url));
          if (fs.existsSync(oldVideoPath)) fs.unlinkSync(oldVideoPath);
          if (old.thumb) {
            const oldThumbPath = path.join(THUMB_DIR, path.basename(old.thumb));
            if (fs.existsSync(oldThumbPath)) fs.unlinkSync(oldThumbPath);
          }
        } catch (e) {
          // Cleanup errors are non-fatal
        }
      }
    }

    saveManifest(manifest);

    console.log(`Auto-reel uploaded: ${name} (${template}) — ${(videoBuffer.length / 1024 / 1024).toFixed(1)}MB`);

    res.json({
      success: true,
      entry,
      totalAutoReels: manifest.videos.length,
    });
  } catch (err) {
    console.error('Auto-reel upload error:', err);
    res.status(500).json({ error: 'Failed to upload auto-reel' });
  }
});

/**
 * GET /api/reels/auto-feed
 * Returns all auto-generated reels (for the main feed to merge in).
 */
router.get('/auto-feed', (req, res) => {
  try {
    const manifest = loadManifest();
    res.json({
      videos: manifest.videos,
      total: manifest.videos.length,
      lastUpdated: manifest.lastUpdated,
    });
  } catch (err) {
    res.status(500).json({ error: 'Failed to load auto-feed' });
  }
});

/**
 * GET /api/reels/auto-video/:filename
 * Stream an auto-generated video with range request support.
 */
router.get('/auto-video/:filename', (req, res) => {
  try {
    const filename = path.basename(req.params.filename); // Prevent path traversal
    const filePath = path.join(UPLOAD_DIR, filename);

    if (!fs.existsSync(filePath)) {
      return res.status(404).json({ error: 'Video not found' });
    }

    const stat = fs.statSync(filePath);
    const fileSize = stat.size;
    const range = req.headers.range;

    if (range) {
      const parts = range.replace(/bytes=/, '').split('-');
      const start = parseInt(parts[0], 10);
      const end = parts[1] ? parseInt(parts[1], 10) : fileSize - 1;
      const chunkSize = end - start + 1;

      res.writeHead(206, {
        'Content-Range': `bytes ${start}-${end}/${fileSize}`,
        'Accept-Ranges': 'bytes',
        'Content-Length': chunkSize,
        'Content-Type': 'video/mp4',
        'Cache-Control': 'public, max-age=3600',
      });
      fs.createReadStream(filePath, { start, end }).pipe(res);
    } else {
      res.writeHead(200, {
        'Content-Length': fileSize,
        'Content-Type': 'video/mp4',
        'Accept-Ranges': 'bytes',
        'Cache-Control': 'public, max-age=3600',
      });
      fs.createReadStream(filePath).pipe(res);
    }
  } catch (err) {
    console.error('Auto-reel stream error:', err);
    res.status(500).json({ error: 'Failed to stream video' });
  }
});

/**
 * GET /api/reels/auto-thumb/:filename
 * Serve a thumbnail image.
 */
router.get('/auto-thumb/:filename', (req, res) => {
  try {
    const filename = path.basename(req.params.filename);
    const filePath = path.join(THUMB_DIR, filename);

    if (!fs.existsSync(filePath)) {
      return res.status(404).json({ error: 'Thumbnail not found' });
    }

    res.writeHead(200, {
      'Content-Type': 'image/webp',
      'Cache-Control': 'public, max-age=86400',
    });
    fs.createReadStream(filePath).pipe(res);
  } catch (err) {
    res.status(500).json({ error: 'Failed to serve thumbnail' });
  }
});

module.exports = router;
